@host = http://localhost:5172

### Get all projects
GET {{host}}/api/task/projects
Accept: application/json

### Add a new project
POST {{host}}/api/task/projects
Content-Type: application/json

{
    "projectName": "secrets"
}

### Add a task to a project
POST {{host}}/api/task/tasks
Content-Type: application/json

{
    "projectName": "secrets",
    "description": "Eat more donuts"
}

### Check a task
PUT {{host}}/api/task/tasks/1/check

### Uncheck a task
PUT {{host}}/api/task/tasks/1/uncheck

### Set task deadline
PUT {{host}}/api/task/tasks/1/deadline
Content-Type: application/json

{
    "deadline": "2024-12-31T00:00:00"
}

### Get today's tasks
GET {{host}}/api/task/tasks/today
Accept: application/json

### Get tasks by deadline
GET {{host}}/api/task/tasks/by-deadline?deadline=2024-12-31T00:00:00
Accept: application/json 